window.BPCL_SAMPLE_DATA = [
  {
    "roid": "116218",
    "outlet_name": "ALTRADE AGENCIES",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116221",
    "outlet_name": "AZAD PETROL & DIESEL OIL DEALE",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.76,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116223",
    "outlet_name": "B.L.PATIL & SONS",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.76,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116226",
    "outlet_name": "GAJANAN PETROL PUMP",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.92,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116227",
    "outlet_name": "HIDKAL AUTOMOBILES",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.58,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116228",
    "outlet_name": "K.A.MAHAJAN",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116229",
    "outlet_name": "P.M.KARIKAZI",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116230",
    "outlet_name": "R.B.KITTURKAR",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.73,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116232",
    "outlet_name": "SHREE LAXMI PETROL STORES",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.63,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116233",
    "outlet_name": "SHRI MANGESH PETROL STORES",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.5,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116235",
    "outlet_name": "S.S.MELLIGERI",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116236",
    "outlet_name": "S.S.MELLIGERI",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116238",
    "outlet_name": "NARAYAN DAS SHAMJI",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 4.0,
    "onl_mpd": 4.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116241",
    "outlet_name": "A.G.PATWARDHAN & SONS",
    "vendor": "ORPAK",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 3.0,
    "onl_mpd": 2.0,
    "onb_tnk": 0.67,
    "onl_tnk": 0.51,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116242",
    "outlet_name": "RAMDURGA AUTO STORES",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116243",
    "outlet_name": "SANGAMESHWAR AUTO SERVICES",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "No"
  },
  {
    "roid": "116247",
    "outlet_name": "B.V.TALATHI & BROTHERS",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 3.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.33,
    "onl_tnk": 0.1,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116248",
    "outlet_name": "THE UGAR SUGAR WORKS LTD.",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 4.0,
    "onl_mpd": 4.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.69,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116249",
    "outlet_name": "V.V.VARDE",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116250",
    "outlet_name": "V.B.SASNOOR",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116251",
    "outlet_name": "V.J.MANJREKAR & SON",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.83,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116252",
    "outlet_name": "T.M.YERUDKAR",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.38,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116253",
    "outlet_name": "SHRI GURUPRASAD FILLING STATIO",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "No"
  },
  {
    "roid": "116256",
    "outlet_name": "C.M. BENNI",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116257",
    "outlet_name": "I.D.BANGARSHETRA & SONS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 4.0,
    "onb_tnk": 1.33,
    "onl_tnk": 0.9,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116259",
    "outlet_name": "B.G.DODDAMANI & BROTHERS",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 2.0,
    "onb_tnk": 0.67,
    "onl_tnk": 0.58,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116261",
    "outlet_name": "H.OBHAN AUTOMOBILES",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.65,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116262",
    "outlet_name": "F.M.HASBI",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.88,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116264",
    "outlet_name": "JYOTHI SERVICE STATION",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116266",
    "outlet_name": "KUNDGOL T.A.P.C.M SOCIETY",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "No"
  },
  {
    "roid": "116267",
    "outlet_name": "T.A.KURATTI",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116269",
    "outlet_name": "MAGAVI CITY FUELS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116270",
    "outlet_name": "SHREE BASAWESHWER AUTO SERVICE",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116271",
    "outlet_name": "T.B.MANVI & SONS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.73,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116272",
    "outlet_name": "S.M. MIRJANKAR & CO.",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116275",
    "outlet_name": "S.C. NAREGAL",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 4.0,
    "onl_mpd": 4.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.57,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116276",
    "outlet_name": "PARIMALA ENTERPRISES",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116278",
    "outlet_name": "S.G.PATIL & CO",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.72,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116279",
    "outlet_name": "G.L.SHETRA",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.72,
    "auto_rsp": "Yes"
  },
  {
    "roid": "116282",
    "outlet_name": "WESTERN GARAGE",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 6.0,
    "onl_mpd": 5.0,
    "onb_tnk": 0.83,
    "onl_tnk": 0.53,
    "auto_rsp": "Yes"
  },
  {
    "roid": "128824",
    "outlet_name": "RENUKA PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.69,
    "auto_rsp": "Yes"
  },
  {
    "roid": "135822",
    "outlet_name": "BP-KOTUR-1",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "135823",
    "outlet_name": "BP-KOTUR-2",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 5.0,
    "onl_mpd": 5.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "138386",
    "outlet_name": "MUJAWAR ROADWAYS",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.72,
    "auto_rsp": "Yes"
  },
  {
    "roid": "138899",
    "outlet_name": "BARDE ROADLINES",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "140644",
    "outlet_name": "ISHWAR PETROLEUM",
    "vendor": "ORPAK",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.79,
    "auto_rsp": "Yes"
  },
  {
    "roid": "140923",
    "outlet_name": "SHREYA AGENCY",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.5,
    "auto_rsp": "Yes"
  },
  {
    "roid": "141349",
    "outlet_name": "DEVEN AGENCIES",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 5.0,
    "onl_mpd": 5.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "141883",
    "outlet_name": "ARAWIND PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "143280",
    "outlet_name": "DESHPANDE PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 4.0,
    "onl_mpd": 2.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.36,
    "auto_rsp": "Yes"
  },
  {
    "roid": "143608",
    "outlet_name": "PUJAR PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.75,
    "auto_rsp": "Yes"
  },
  {
    "roid": "143741",
    "outlet_name": "SHREE JAGADGURU TONTADARYA PRA",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.56,
    "auto_rsp": "Yes"
  },
  {
    "roid": "146461",
    "outlet_name": "SRI. VEERABHADRESHWAR PETROLEU",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.54,
    "auto_rsp": "Yes"
  },
  {
    "roid": "146845",
    "outlet_name": "NETRAVATHI SERVICE STATION",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.75,
    "auto_rsp": "Yes"
  },
  {
    "roid": "147239",
    "outlet_name": "P.C.KUBIHAL & BROS.FUELLING ST",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.75,
    "auto_rsp": "Yes"
  },
  {
    "roid": "147485",
    "outlet_name": "SHRI PARISHWANATH PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "147490",
    "outlet_name": "SHRI VIGNESHWAR TRADERS",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.38,
    "auto_rsp": "Yes"
  },
  {
    "roid": "147536",
    "outlet_name": "SRI BASAVESHWAR PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.77,
    "auto_rsp": "Yes"
  },
  {
    "roid": "147677",
    "outlet_name": "DEVENDRA FILLING STATION",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.69,
    "auto_rsp": "Yes"
  },
  {
    "roid": "148767",
    "outlet_name": "RAMESHWAR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.9,
    "auto_rsp": "Yes"
  },
  {
    "roid": "148968",
    "outlet_name": "SHRI LAKSHMI PETROLEUM",
    "vendor": "ORPAK",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.73,
    "auto_rsp": "Yes"
  },
  {
    "roid": "149690",
    "outlet_name": "R.B.KITTURKAR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 5.0,
    "onl_mpd": 5.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "149793",
    "outlet_name": "M.P.KARIKAZI",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "149794",
    "outlet_name": "GOGTE PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 4.0,
    "onl_mpd": 4.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "149816",
    "outlet_name": "RANI CHANNAMMA PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.63,
    "auto_rsp": "Yes"
  },
  {
    "roid": "150282",
    "outlet_name": "LAXMI NARASINHA AGENCIES",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.58,
    "auto_rsp": "Yes"
  },
  {
    "roid": "150741",
    "outlet_name": "ITNAL PETROLEUM",
    "vendor": "ORPAK",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.58,
    "auto_rsp": "Yes"
  },
  {
    "roid": "154864",
    "outlet_name": "JAI HANUMAN PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.92,
    "auto_rsp": "Yes"
  },
  {
    "roid": "155543",
    "outlet_name": "V. T. FUEL STATION",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.75,
    "auto_rsp": "Yes"
  },
  {
    "roid": "156576",
    "outlet_name": "SHIVAM PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.75,
    "auto_rsp": "Yes"
  },
  {
    "roid": "157520",
    "outlet_name": "SRI SAI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.58,
    "auto_rsp": "Yes"
  },
  {
    "roid": "158207",
    "outlet_name": "BP-RANEBENNUR - I",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 4.0,
    "onl_mpd": 3.0,
    "onb_tnk": 0.75,
    "onl_tnk": 0.7,
    "auto_rsp": "Yes"
  },
  {
    "roid": "159799",
    "outlet_name": "SRI SIDDHA RUDHA PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.69,
    "auto_rsp": "Yes"
  },
  {
    "roid": "159845",
    "outlet_name": "NATIONAL PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.63,
    "auto_rsp": "Yes"
  },
  {
    "roid": "159846",
    "outlet_name": "S.B.KARADI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "159898",
    "outlet_name": "KIWAD PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "160030",
    "outlet_name": "RITESH PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "160151",
    "outlet_name": "SHRI GURUKARIBASAVESHWARA F S",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.52,
    "auto_rsp": "Yes"
  },
  {
    "roid": "160518",
    "outlet_name": "A.B. PARVATRAO PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 4.0,
    "onl_mpd": 4.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "162012",
    "outlet_name": "OM SAIKRISHNA PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.65,
    "auto_rsp": "Yes"
  },
  {
    "roid": "162392",
    "outlet_name": "BP-KOGNOLLI",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 11.0,
    "onl_mpd": 9.0,
    "onb_tnk": 0.82,
    "onl_tnk": 0.73,
    "auto_rsp": "Yes"
  },
  {
    "roid": "163073",
    "outlet_name": "OM SAI RAM PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.69,
    "auto_rsp": "Yes"
  },
  {
    "roid": "163252",
    "outlet_name": "THE GSE&SS CO-OP SOCIETY LTD.",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "No"
  },
  {
    "roid": "163404",
    "outlet_name": "KALLUR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "163707",
    "outlet_name": "R.T.PATIL PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.56,
    "auto_rsp": "Yes"
  },
  {
    "roid": "166290",
    "outlet_name": "SHRI DESHPANDE PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "167890",
    "outlet_name": "GORAL PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.64,
    "auto_rsp": "Yes"
  },
  {
    "roid": "167902",
    "outlet_name": "KIRAN AUTO",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "167982",
    "outlet_name": "S.C.PANCHAKATTIMATH PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.9,
    "auto_rsp": "Yes"
  },
  {
    "roid": "168550",
    "outlet_name": "VANASHREE PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.58,
    "auto_rsp": "Yes"
  },
  {
    "roid": "169328",
    "outlet_name": "SHRI LAXMI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "170051",
    "outlet_name": "ALIYA PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "170107",
    "outlet_name": "KARTRU FAKEERESHWAR SERVICE CE",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.63,
    "auto_rsp": "Yes"
  },
  {
    "roid": "170368",
    "outlet_name": "SHAHAPUR PETROLEUM",
    "vendor": "ORPAK",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "171700",
    "outlet_name": "VEERABHADRESWAR PETROLEUM SERV",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.96,
    "auto_rsp": "Yes"
  },
  {
    "roid": "172069",
    "outlet_name": "JAYALAXMI PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.63,
    "auto_rsp": "Yes"
  },
  {
    "roid": "173201",
    "outlet_name": "SHIVGEET PETROLEUM",
    "vendor": "ORPAK",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.65,
    "auto_rsp": "Yes"
  },
  {
    "roid": "173202",
    "outlet_name": "ANNAPURNESHWARI PETROLEUM",
    "vendor": "ORPAK",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "173942",
    "outlet_name": "SHREE DEVI PETROLEUM",
    "vendor": "ORPAK",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.25,
    "auto_rsp": "Yes"
  },
  {
    "roid": "173943",
    "outlet_name": "SHREE REVANSHIDDESHWAR PETROLE",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.79,
    "auto_rsp": "Yes"
  },
  {
    "roid": "173944",
    "outlet_name": "HALADOTAR PETROLEUM",
    "vendor": "ORPAK",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.75,
    "auto_rsp": "Yes"
  },
  {
    "roid": "173945",
    "outlet_name": "SHASHANK PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.63,
    "auto_rsp": "Yes"
  },
  {
    "roid": "173968",
    "outlet_name": "PALLAVI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.73,
    "auto_rsp": "Yes"
  },
  {
    "roid": "173999",
    "outlet_name": "SHREE RENUKA DEVI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 2.0,
    "onb_tnk": 0.67,
    "onl_tnk": 0.46,
    "auto_rsp": "Yes"
  },
  {
    "roid": "174322",
    "outlet_name": "VENKATESH PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.35,
    "auto_rsp": "Yes"
  },
  {
    "roid": "174324",
    "outlet_name": "MURAGESH PETROLEUM",
    "vendor": "ORPAK",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "174577",
    "outlet_name": "SHREE TULAJABHAVANI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "174617",
    "outlet_name": "RAVGANGA PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "174618",
    "outlet_name": "MUJAWAR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.54,
    "auto_rsp": "Yes"
  },
  {
    "roid": "174688",
    "outlet_name": "ILAGER FUEL CENTER",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.69,
    "auto_rsp": "Yes"
  },
  {
    "roid": "174689",
    "outlet_name": "SRI VEERABHADRESHWAR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "174691",
    "outlet_name": "JABBAR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 4.0,
    "onb_tnk": 1.33,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "174734",
    "outlet_name": "SHRI SAI RAM PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.35,
    "auto_rsp": "Yes"
  },
  {
    "roid": "174810",
    "outlet_name": "B S KALLUR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.51,
    "auto_rsp": "Yes"
  },
  {
    "roid": "174819",
    "outlet_name": "SRI GURUSIDDAPRABHUDEVARU PETR",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 2.0,
    "onb_tnk": 0.67,
    "onl_tnk": 0.46,
    "auto_rsp": "Yes"
  },
  {
    "roid": "175102",
    "outlet_name": "SHRINIVAS PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.35,
    "auto_rsp": "Yes"
  },
  {
    "roid": "175244",
    "outlet_name": "HUNASHIKATTI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 2.0,
    "onb_tnk": 2.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "175245",
    "outlet_name": "SHRI LAXMI VENKATESHWAR PETROL",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "176182",
    "outlet_name": "GUNJIKAR PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "176223",
    "outlet_name": "SHRI MAYAKKADEVI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.73,
    "auto_rsp": "Yes"
  },
  {
    "roid": "176327",
    "outlet_name": "SHRI VINAYAK PETROL PUMP",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "No"
  },
  {
    "roid": "176328",
    "outlet_name": "REVANASIDDESHWAR PETROLEUM",
    "vendor": "ORPAK",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.85,
    "auto_rsp": "Yes"
  },
  {
    "roid": "176349",
    "outlet_name": "SHRI HANUMAN PETROLEUM",
    "vendor": "ORPAK",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "176373",
    "outlet_name": "NIMBA CITY PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.52,
    "auto_rsp": "Yes"
  },
  {
    "roid": "176375",
    "outlet_name": "S. S. KULKARNI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.38,
    "auto_rsp": "Yes"
  },
  {
    "roid": "176376",
    "outlet_name": "MSTONES",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.35,
    "auto_rsp": "Yes"
  },
  {
    "roid": "176377",
    "outlet_name": "SHREE KANAKA PETROLEUM",
    "vendor": "ORPAK",
    "sales_area": "Haveri Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "176378",
    "outlet_name": "ADARSH PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "No"
  },
  {
    "roid": "176386",
    "outlet_name": "NETRAVATI PETROLEUM",
    "vendor": "ORPAK",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "177338",
    "outlet_name": "ANNAPURNESHWARI FUELS",
    "vendor": "ORPAK",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.81,
    "auto_rsp": "Yes"
  },
  {
    "roid": "177427",
    "outlet_name": "SHRI MAHALINGESHWAR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "177876",
    "outlet_name": "SHREE MALLIKARJUN TRADING CO.",
    "vendor": "ORPAK",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.65,
    "auto_rsp": "Yes"
  },
  {
    "roid": "178311",
    "outlet_name": "SRI BASAVESHWAR PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.63,
    "auto_rsp": "Yes"
  },
  {
    "roid": "178378",
    "outlet_name": "SHRI MALATESH OIL TRADERS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.54,
    "auto_rsp": "Yes"
  },
  {
    "roid": "178401",
    "outlet_name": "HUGGI PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.35,
    "auto_rsp": "Yes"
  },
  {
    "roid": "178457",
    "outlet_name": "SATYA RAM PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "178925",
    "outlet_name": "SHRI SAI PETROLEUM",
    "vendor": "ORPAK",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "179740",
    "outlet_name": "SMT. GANGAMMA S. PATIL MEMORIA",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "179832",
    "outlet_name": "AL MEHBOOB PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "180181",
    "outlet_name": "SHRI MAHALAXMI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "180288",
    "outlet_name": "BASAVA JYOTI PETROLEUM",
    "vendor": "ORPAK",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.69,
    "auto_rsp": "Yes"
  },
  {
    "roid": "180298",
    "outlet_name": "BRAHMADEV PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.35,
    "auto_rsp": "Yes"
  },
  {
    "roid": "180299",
    "outlet_name": "NERLIKAR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "180300",
    "outlet_name": "TIRTH PETROLEUM",
    "vendor": "ORPAK",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.79,
    "auto_rsp": "Yes"
  },
  {
    "roid": "180301",
    "outlet_name": "DESAI BROTHERS",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.33,
    "onl_tnk": 0.25,
    "auto_rsp": "Yes"
  },
  {
    "roid": "181600",
    "outlet_name": "NAIKAR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.46,
    "auto_rsp": "Yes"
  },
  {
    "roid": "181985",
    "outlet_name": "ROHIT PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.33,
    "auto_rsp": "Yes"
  },
  {
    "roid": "182420",
    "outlet_name": "V B S",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.35,
    "auto_rsp": "Yes"
  },
  {
    "roid": "182422",
    "outlet_name": "M P URABHINAVAR PETROLEUMS",
    "vendor": "ORPAK",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.88,
    "auto_rsp": "Yes"
  },
  {
    "roid": "182589",
    "outlet_name": "SHARADAMBIKA PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.75,
    "auto_rsp": "Yes"
  },
  {
    "roid": "182646",
    "outlet_name": "SHANMUKH PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.75,
    "auto_rsp": "Yes"
  },
  {
    "roid": "183501",
    "outlet_name": "SHRI MALTESH PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "183502",
    "outlet_name": "SHREE LAXMI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "183503",
    "outlet_name": "SHREE NIDHI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "183511",
    "outlet_name": "SHIVAKASHI & SONS PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "183534",
    "outlet_name": "KEERTI PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "183535",
    "outlet_name": "BASAVASHREE PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.6,
    "auto_rsp": "Yes"
  },
  {
    "roid": "183536",
    "outlet_name": "P. V. PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.44,
    "auto_rsp": "Yes"
  },
  {
    "roid": "183537",
    "outlet_name": "NIKHIL PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "183538",
    "outlet_name": "DESAI PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.79,
    "auto_rsp": "Yes"
  },
  {
    "roid": "183667",
    "outlet_name": "SHREE KALMESHWAR PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.65,
    "auto_rsp": "Yes"
  },
  {
    "roid": "183668",
    "outlet_name": "DANESWARI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "183708",
    "outlet_name": "BHAVANI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "183803",
    "outlet_name": "SHIDESHWAR PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "183949",
    "outlet_name": "SANGMESHWAR PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.33,
    "auto_rsp": "Yes"
  },
  {
    "roid": "184086",
    "outlet_name": "RAHUL PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.35,
    "auto_rsp": "Yes"
  },
  {
    "roid": "184087",
    "outlet_name": "BASAVASHREE PETROLEUM",
    "vendor": "ORPAK",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "No"
  },
  {
    "roid": "184191",
    "outlet_name": "JAYAM PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 4.0,
    "onl_mpd": 4.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.57,
    "auto_rsp": "Yes"
  },
  {
    "roid": "184193",
    "outlet_name": "PAWAR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.06,
    "auto_rsp": "Yes"
  },
  {
    "roid": "185357",
    "outlet_name": "NEELAMMA PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.44,
    "auto_rsp": "Yes"
  },
  {
    "roid": "185375",
    "outlet_name": "ANNAPOORNESWARI FUELS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.63,
    "auto_rsp": "Yes"
  },
  {
    "roid": "185442",
    "outlet_name": "MRUTHYUNJAYA PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.73,
    "auto_rsp": "Yes"
  },
  {
    "roid": "185448",
    "outlet_name": "SRI MALTESH PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.6,
    "auto_rsp": "Yes"
  },
  {
    "roid": "185539",
    "outlet_name": "SHREE HARI OM PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.42,
    "auto_rsp": "Yes"
  },
  {
    "roid": "185748",
    "outlet_name": "HIREMATH PETROL BUNK",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "185865",
    "outlet_name": "SHRI AMARESHWAR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.33,
    "auto_rsp": "Yes"
  },
  {
    "roid": "186105",
    "outlet_name": "DURGALAXMI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "186121",
    "outlet_name": "OM PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.56,
    "auto_rsp": "Yes"
  },
  {
    "roid": "186713",
    "outlet_name": "MORE PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "187575",
    "outlet_name": "BUTALI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.75,
    "auto_rsp": "Yes"
  },
  {
    "roid": "188223",
    "outlet_name": "S D ATAWALAGI",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "No"
  },
  {
    "roid": "188602",
    "outlet_name": "SAI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 2.0,
    "onb_tnk": 0.67,
    "onl_tnk": 0.5,
    "auto_rsp": "Yes"
  },
  {
    "roid": "190040",
    "outlet_name": "KIRAN PETROLEUM",
    "vendor": "ORPAK",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.65,
    "auto_rsp": "Yes"
  },
  {
    "roid": "192576",
    "outlet_name": "BASAVESHWAR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "193819",
    "outlet_name": "BOLANNAVAR PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "194240",
    "outlet_name": "VENKATESHWAR PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "194274",
    "outlet_name": "BP RANEBENNUR II",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.96,
    "auto_rsp": "Yes"
  },
  {
    "roid": "194414",
    "outlet_name": "VIJAYALAXMI PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "195314",
    "outlet_name": "NOOR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.54,
    "auto_rsp": "Yes"
  },
  {
    "roid": "196368",
    "outlet_name": "R P GULMI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.49,
    "auto_rsp": "Yes"
  },
  {
    "roid": "196373",
    "outlet_name": "SHRI MAHALAXMI PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "200277",
    "outlet_name": "RANVEER PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "200530",
    "outlet_name": "SHRI DANESHWARI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.75,
    "auto_rsp": "Yes"
  },
  {
    "roid": "200748",
    "outlet_name": "SHAURYA PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "202300",
    "outlet_name": "AVADHUT PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.88,
    "auto_rsp": "Yes"
  },
  {
    "roid": "205603",
    "outlet_name": "VIJAYALAXMI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.92,
    "auto_rsp": "Yes"
  },
  {
    "roid": "206094",
    "outlet_name": "SHRIMAHALAXMI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.83,
    "auto_rsp": "Yes"
  },
  {
    "roid": "210275",
    "outlet_name": "NYAMAGOUDAR PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "210539",
    "outlet_name": "SMT SUSHEELAMMA.S.PATIL MEMORI",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.5,
    "onl_tnk": 0.75,
    "auto_rsp": "Yes"
  },
  {
    "roid": "210715",
    "outlet_name": "JANNU PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.83,
    "auto_rsp": "Yes"
  },
  {
    "roid": "210997",
    "outlet_name": "SHIVABASAV PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "211372",
    "outlet_name": "ATHARV PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.69,
    "auto_rsp": "Yes"
  },
  {
    "roid": "211382",
    "outlet_name": "ADVIK PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.54,
    "auto_rsp": "Yes"
  },
  {
    "roid": "211402",
    "outlet_name": "ATTAR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "211867",
    "outlet_name": "KAVERI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.79,
    "auto_rsp": "Yes"
  },
  {
    "roid": "212311",
    "outlet_name": "SHRI LAXMINARAYAN PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.46,
    "auto_rsp": "Yes"
  },
  {
    "roid": "213054",
    "outlet_name": "DIXIT AGENCIES",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.33,
    "auto_rsp": "Yes"
  },
  {
    "roid": "213060",
    "outlet_name": "POOJA PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.69,
    "auto_rsp": "Yes"
  },
  {
    "roid": "213453",
    "outlet_name": "MAHALAXMI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "213475",
    "outlet_name": "SHRI SOMNATH PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.65,
    "auto_rsp": "Yes"
  },
  {
    "roid": "214016",
    "outlet_name": "SHRI ANJANEYA SMART FUELS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.35,
    "auto_rsp": "Yes"
  },
  {
    "roid": "214116",
    "outlet_name": "BHAVESHWARI PETROLIUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.63,
    "auto_rsp": "Yes"
  },
  {
    "roid": "214177",
    "outlet_name": "VANARAJ PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "No"
  },
  {
    "roid": "214239",
    "outlet_name": "SHRI VINAYAK PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.58,
    "auto_rsp": "Yes"
  },
  {
    "roid": "214248",
    "outlet_name": "SHRI VENKATESHWARA PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "214279",
    "outlet_name": "PATIL PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "214283",
    "outlet_name": "BARKI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.29,
    "auto_rsp": "Yes"
  },
  {
    "roid": "214288",
    "outlet_name": "J G PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.13,
    "auto_rsp": "Yes"
  },
  {
    "roid": "214333",
    "outlet_name": "APPAJI PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.78,
    "auto_rsp": "Yes"
  },
  {
    "roid": "214355",
    "outlet_name": "NYAMAGOUDAR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.75,
    "auto_rsp": "Yes"
  },
  {
    "roid": "214418",
    "outlet_name": "NISARGA PRIYA PUMP",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.81,
    "auto_rsp": "Yes"
  },
  {
    "roid": "214985",
    "outlet_name": "ADVIK SONAKSHI FUELS",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.58,
    "auto_rsp": "Yes"
  },
  {
    "roid": "215000",
    "outlet_name": "NAROOTE PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.88,
    "auto_rsp": "Yes"
  },
  {
    "roid": "215034",
    "outlet_name": "SONAKSHI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.17,
    "auto_rsp": "Yes"
  },
  {
    "roid": "215036",
    "outlet_name": "SAROJA PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.58,
    "auto_rsp": "Yes"
  },
  {
    "roid": "215063",
    "outlet_name": "TULAJABHAVANI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.69,
    "auto_rsp": "Yes"
  },
  {
    "roid": "215064",
    "outlet_name": "SUVARANA PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.65,
    "auto_rsp": "Yes"
  },
  {
    "roid": "215084",
    "outlet_name": "GURU PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "No"
  },
  {
    "roid": "215698",
    "outlet_name": "SHRI JAGANNATH PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.73,
    "auto_rsp": "Yes"
  },
  {
    "roid": "215703",
    "outlet_name": "ASHA BHARATI PETRO LINKS",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "215922",
    "outlet_name": "PAVANAJA PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.31,
    "auto_rsp": "Yes"
  },
  {
    "roid": "216999",
    "outlet_name": "VIJAY PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.6,
    "auto_rsp": "Yes"
  },
  {
    "roid": "217253",
    "outlet_name": "ROOPALI SERVICE CENTER",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 4.0,
    "onl_mpd": 4.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.79,
    "auto_rsp": "Yes"
  },
  {
    "roid": "217267",
    "outlet_name": "SRI BASAVA FILLING STATION",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.48,
    "auto_rsp": "Yes"
  },
  {
    "roid": "217590",
    "outlet_name": "NYAMAGOUDAR PETROLEUMS KUNCHAN",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "217642",
    "outlet_name": "SHRI CHANNAGIRESHWAR PETROLIUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.75,
    "auto_rsp": "Yes"
  },
  {
    "roid": "217962",
    "outlet_name": "SHRI GURU SANGAMESHWAR PETROLE",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "218199",
    "outlet_name": "KARUDI SMART FUELS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.5,
    "auto_rsp": "Yes"
  },
  {
    "roid": "218200",
    "outlet_name": "MALLIKARJUN PETROL PUMP",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.65,
    "auto_rsp": "Yes"
  },
  {
    "roid": "218229",
    "outlet_name": "SAI BABA PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.5,
    "auto_rsp": "Yes"
  },
  {
    "roid": "218309",
    "outlet_name": "SHRI ARIHANT PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "No"
  },
  {
    "roid": "218390",
    "outlet_name": "SHRISHTI PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.65,
    "auto_rsp": "Yes"
  },
  {
    "roid": "218430",
    "outlet_name": "SAI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 1.0,
    "onl_mpd": 2.0,
    "onb_tnk": 2.0,
    "onl_tnk": 0.92,
    "auto_rsp": "Yes"
  },
  {
    "roid": "218431",
    "outlet_name": "BALAJI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 4.0,
    "onl_mpd": 4.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "219103",
    "outlet_name": "SHRI ADAVISIDDESHWAR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.17,
    "auto_rsp": "No"
  },
  {
    "roid": "219105",
    "outlet_name": "RAJ PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.72,
    "auto_rsp": "Yes"
  },
  {
    "roid": "219162",
    "outlet_name": "SIDDHASWAROOP FUEL POINT",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.79,
    "auto_rsp": "Yes"
  },
  {
    "roid": "219216",
    "outlet_name": "SHRI MAHALAXMI PETROLEUMS- 1",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "219219",
    "outlet_name": "GOUTAM PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.98,
    "auto_rsp": "Yes"
  },
  {
    "roid": "219401",
    "outlet_name": "GANGA GANESH FILLING STATION",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.69,
    "auto_rsp": "Yes"
  },
  {
    "roid": "219426",
    "outlet_name": "SHREE SAI PETROLS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.63,
    "auto_rsp": "Yes"
  },
  {
    "roid": "221406",
    "outlet_name": "SHRI ARANYA SIDDESHWAR PETROLE",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "221680",
    "outlet_name": "VIMALESHWARA PETROL PUMP",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "221738",
    "outlet_name": "UPPIN MASTER PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "No"
  },
  {
    "roid": "221899",
    "outlet_name": "KUMBAR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "222269",
    "outlet_name": "SHREE BASAVESHWAR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.92,
    "auto_rsp": "Yes"
  },
  {
    "roid": "222392",
    "outlet_name": "GOLASHETTI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "No"
  },
  {
    "roid": "222701",
    "outlet_name": "VEERALINGAYYANAMATH AND COMPAN",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.73,
    "auto_rsp": "Yes"
  },
  {
    "roid": "222880",
    "outlet_name": "SHREE SAI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 2.0,
    "onb_tnk": 2.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "222916",
    "outlet_name": "S.S.MELLIGERI",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "223506",
    "outlet_name": "BP-KESHAWAPUR",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.96,
    "auto_rsp": "Yes"
  },
  {
    "roid": "223544",
    "outlet_name": "SRINIVASA PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "224666",
    "outlet_name": "SHRI BASAV PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.5,
    "auto_rsp": "Yes"
  },
  {
    "roid": "224667",
    "outlet_name": "YASHODHARA PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.56,
    "auto_rsp": "Yes"
  },
  {
    "roid": "224761",
    "outlet_name": "SHRI DURADUNDESHWAR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.4,
    "auto_rsp": "Yes"
  },
  {
    "roid": "224777",
    "outlet_name": "AASHIRWAD FUELS",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.69,
    "auto_rsp": "Yes"
  },
  {
    "roid": "225047",
    "outlet_name": "SHIVASHAKTI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "225352",
    "outlet_name": "SRI JAGAJYOTI BASAVESHWAR PETR",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "225410",
    "outlet_name": "SHREE MAHALAXMI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.46,
    "auto_rsp": "Yes"
  },
  {
    "roid": "225655",
    "outlet_name": "SHRI PATIL & SON'S PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.73,
    "auto_rsp": "Yes"
  },
  {
    "roid": "225680",
    "outlet_name": "BAARAKHUDA PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "225903",
    "outlet_name": "RASHTRAKUTA PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.4,
    "auto_rsp": "Yes"
  },
  {
    "roid": "225935",
    "outlet_name": "KWALITY FUELS",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "No"
  },
  {
    "roid": "226421",
    "outlet_name": "SHRI KAMAGIRI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.1,
    "auto_rsp": "Yes"
  },
  {
    "roid": "226446",
    "outlet_name": "SHIVA SERVICE STATION",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.21,
    "auto_rsp": "Yes"
  },
  {
    "roid": "226515",
    "outlet_name": "SHREE SIDDHI VINAYAKA PETROLEU",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.58,
    "auto_rsp": "Yes"
  },
  {
    "roid": "226516",
    "outlet_name": "SHRI MAHALINGESHWAR PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.75,
    "auto_rsp": "Yes"
  },
  {
    "roid": "226534",
    "outlet_name": "NEERALAGI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.6,
    "auto_rsp": "Yes"
  },
  {
    "roid": "226535",
    "outlet_name": "SAMARTH FUELPOINT",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.29,
    "auto_rsp": "Yes"
  },
  {
    "roid": "226562",
    "outlet_name": "SHARIF PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.69,
    "auto_rsp": "Yes"
  },
  {
    "roid": "227771",
    "outlet_name": "ILAGER PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.69,
    "auto_rsp": "Yes"
  },
  {
    "roid": "228062",
    "outlet_name": "SHRI HERAMB PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.58,
    "auto_rsp": "Yes"
  },
  {
    "roid": "228128",
    "outlet_name": "BHAGYALAXMI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.81,
    "auto_rsp": "Yes"
  },
  {
    "roid": "228253",
    "outlet_name": "SHRI MAHALINGESHWAR PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.92,
    "auto_rsp": "Yes"
  },
  {
    "roid": "228312",
    "outlet_name": "RENUKADEVI PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.63,
    "auto_rsp": "Yes"
  },
  {
    "roid": "228431",
    "outlet_name": "JANNU PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "No"
  },
  {
    "roid": "228508",
    "outlet_name": "NAMAKKAL GANESH FUELS",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.82,
    "auto_rsp": "Yes"
  },
  {
    "roid": "228911",
    "outlet_name": "J P PATIL PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "229501",
    "outlet_name": "PAARVATI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.63,
    "auto_rsp": "Yes"
  },
  {
    "roid": "229641",
    "outlet_name": "SAKSHI PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.65,
    "auto_rsp": "Yes"
  },
  {
    "roid": "230300",
    "outlet_name": "ANNADANI PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "231287",
    "outlet_name": "IDEAL PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.6,
    "auto_rsp": "Yes"
  },
  {
    "roid": "232322",
    "outlet_name": "SIDDAPPA HIPPARAGI (MRN) PETRO",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.75,
    "auto_rsp": "Yes"
  },
  {
    "roid": "232688",
    "outlet_name": "TONGALI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "232690",
    "outlet_name": "BP-BELGAUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.89,
    "auto_rsp": "Yes"
  },
  {
    "roid": "233737",
    "outlet_name": "SHRI SIDDHESHWAR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "233772",
    "outlet_name": "AVALAKKI PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.68,
    "auto_rsp": "Yes"
  },
  {
    "roid": "234757",
    "outlet_name": "S.K.RATHOD PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.96,
    "auto_rsp": "Yes"
  },
  {
    "roid": "235078",
    "outlet_name": "DESAI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "235188",
    "outlet_name": "JOSHI PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.57,
    "auto_rsp": "Yes"
  },
  {
    "roid": "236245",
    "outlet_name": "ADARSH PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "236532",
    "outlet_name": "PENDARI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "237465",
    "outlet_name": "SAI FUELS",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.1,
    "auto_rsp": "No"
  },
  {
    "roid": "238159",
    "outlet_name": "HUBBALLI FUELS",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.78,
    "auto_rsp": "Yes"
  },
  {
    "roid": "238257",
    "outlet_name": "SURYAKIRAN PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.67,
    "auto_rsp": "Yes"
  },
  {
    "roid": "238971",
    "outlet_name": "DOODHGANGA PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.38,
    "auto_rsp": "Yes"
  },
  {
    "roid": "238982",
    "outlet_name": "NYAMAGOUDAR PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.33,
    "auto_rsp": "Yes"
  },
  {
    "roid": "239042",
    "outlet_name": "SEVALAL PETROLIUMS",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.35,
    "auto_rsp": "Yes"
  },
  {
    "roid": "239271",
    "outlet_name": "M G HINDALGEKAR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.72,
    "auto_rsp": "Yes"
  },
  {
    "roid": "240288",
    "outlet_name": "SHRI PARMANAND PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.69,
    "auto_rsp": "Yes"
  },
  {
    "roid": "240348",
    "outlet_name": "BP-BELGAUM CITY",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "240726",
    "outlet_name": "SHRI BRAHMANATH PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.9,
    "auto_rsp": "Yes"
  },
  {
    "roid": "240797",
    "outlet_name": "SHREE KALASAMMADEVI PETROLIEMS",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.96,
    "auto_rsp": "Yes"
  },
  {
    "roid": "240973",
    "outlet_name": "RADDI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.9,
    "auto_rsp": "Yes"
  },
  {
    "roid": "241623",
    "outlet_name": "MAHATI PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "241740",
    "outlet_name": "S.S.B PETROLEUM'S",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.65,
    "auto_rsp": "Yes"
  },
  {
    "roid": "242119",
    "outlet_name": "MAHALASA FILLING STATION",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.73,
    "auto_rsp": "Yes"
  },
  {
    "roid": "244774",
    "outlet_name": "ANJANEYA FUELS",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "244833",
    "outlet_name": "SHRI SIDDALINGA SHIVAYOGI PETR",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "No"
  },
  {
    "roid": "244925",
    "outlet_name": "PARVATI PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "245274",
    "outlet_name": "MAHALAXMI FUEL PARK",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.79,
    "auto_rsp": "Yes"
  },
  {
    "roid": "245737",
    "outlet_name": "GIRIJABASAVA PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.48,
    "auto_rsp": "Yes"
  },
  {
    "roid": "245891",
    "outlet_name": "SIDDIVINAYAK PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.35,
    "auto_rsp": "Yes"
  },
  {
    "roid": "245920",
    "outlet_name": "SHREE SAI PETROLEUM'S",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.42,
    "auto_rsp": "Yes"
  },
  {
    "roid": "246386",
    "outlet_name": "SRI SAI FUEL STATION",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "246387",
    "outlet_name": "R.H.PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.58,
    "auto_rsp": "Yes"
  },
  {
    "roid": "246774",
    "outlet_name": "BELGAUM SUGARS PRIVATE LIMITED",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.78,
    "auto_rsp": "Yes"
  },
  {
    "roid": "246820",
    "outlet_name": "PATIL PETROL PUMP",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.65,
    "auto_rsp": "Yes"
  },
  {
    "roid": "247411",
    "outlet_name": "DEVAASHISH PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.69,
    "auto_rsp": "Yes"
  },
  {
    "roid": "248098",
    "outlet_name": "SHRI DHANESHWARI PETROLEUM",
    "vendor": "GEMS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "248758",
    "outlet_name": "SAI NACHIKET PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.73,
    "auto_rsp": "Yes"
  },
  {
    "roid": "248759",
    "outlet_name": "AMBIKA PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.75,
    "auto_rsp": "Yes"
  },
  {
    "roid": "249232",
    "outlet_name": "SOUBHAGYALAXMI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.69,
    "auto_rsp": "Yes"
  },
  {
    "roid": "249233",
    "outlet_name": "BALAJI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.75,
    "auto_rsp": "Yes"
  },
  {
    "roid": "249812",
    "outlet_name": "KALIKADEVI PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.58,
    "auto_rsp": "Yes"
  },
  {
    "roid": "249893",
    "outlet_name": "NAYAK PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.79,
    "auto_rsp": "Yes"
  },
  {
    "roid": "250317",
    "outlet_name": "R.A. SANSI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.65,
    "auto_rsp": "Yes"
  },
  {
    "roid": "250415",
    "outlet_name": "SHRI HALASIDDESHWAR PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.73,
    "auto_rsp": "Yes"
  },
  {
    "roid": "250422",
    "outlet_name": "T. R. ASSOCIATES",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "250433",
    "outlet_name": "SHRI SHIVBASAV ONE",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.52,
    "auto_rsp": "Yes"
  },
  {
    "roid": "251643",
    "outlet_name": "BALAJI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "251768",
    "outlet_name": "GUNJIKAR ENERGIZ",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "251824",
    "outlet_name": "SRI MAILARLINGESHWARA PETROLEU",
    "vendor": "GEMS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "252291",
    "outlet_name": "SHRI VENKATESHWAR PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "252674",
    "outlet_name": "RAGHAVENDRA PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "252686",
    "outlet_name": "S N GODI PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 3.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "253500",
    "outlet_name": "SHREE HOLEMMA PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "254187",
    "outlet_name": "SHIVNANDI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "254279",
    "outlet_name": "KAVITARAJ PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "254281",
    "outlet_name": "GK PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "255107",
    "outlet_name": "JAI GOMATESH PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "255138",
    "outlet_name": "TADASAD PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "255143",
    "outlet_name": "MALAGI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "255199",
    "outlet_name": "SRI KANTESHA FUEL STATION",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "255817",
    "outlet_name": "SHREE GURU ADAVISWAMI PETROLEU",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 0.0,
    "onb_tnk": 0.0,
    "onl_tnk": 0.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "255985",
    "outlet_name": "MAHALAXMI FUEL CENTER",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "256021",
    "outlet_name": "DURGA PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur 2 Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.5,
    "auto_rsp": "Yes"
  },
  {
    "roid": "256037",
    "outlet_name": "SHRI SHAKHAMBARI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "256066",
    "outlet_name": "SHARDA PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 5.0,
    "onl_mpd": 2.0,
    "onb_tnk": 0.4,
    "onl_tnk": 0.4,
    "auto_rsp": "Yes"
  },
  {
    "roid": "256740",
    "outlet_name": "GAJALAKSHMI PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "256743",
    "outlet_name": "SRI LAKSHMI VENKATESHWARA PETR",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 1.0,
    "onb_tnk": 0.5,
    "onl_tnk": 0.5,
    "auto_rsp": "Yes"
  },
  {
    "roid": "256888",
    "outlet_name": "PAWAR PETROLEUM ADHOC",
    "vendor": "PINELABS",
    "sales_area": "Dharwad Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.71,
    "auto_rsp": "Yes"
  },
  {
    "roid": "258183",
    "outlet_name": "UNITED ENERGY AND FUELS",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "259016",
    "outlet_name": "VEERABHADRESHWAR PETROLEUM",
    "vendor": "PINELABS",
    "sales_area": "Haveri Retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 1.0,
    "auto_rsp": "Yes"
  },
  {
    "roid": "259120",
    "outlet_name": "AZAD PET & DIE OIL DEALERS ADH",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.76,
    "auto_rsp": "Yes"
  },
  {
    "roid": "259488",
    "outlet_name": "SHRI MAHALINGESHWAR PETROLEUMS",
    "vendor": "PINELABS",
    "sales_area": "Desur Retail",
    "onb_mpd": 3.0,
    "onl_mpd": 3.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.47,
    "auto_rsp": "Yes"
  },
  {
    "roid": "263415",
    "outlet_name": "SHREE BASAVESHWAR PETROLEUM AD",
    "vendor": "PINELABS",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 2.0,
    "onl_mpd": 2.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.69,
    "auto_rsp": "Yes"
  },
  {
    "roid": "264998",
    "outlet_name": "S.S.MELLIGERI ADHOC",
    "vendor": "ORPAK",
    "sales_area": "Bagalkot-retail",
    "onb_mpd": 1.0,
    "onl_mpd": 1.0,
    "onb_tnk": 1.0,
    "onl_tnk": 0.75,
    "auto_rsp": "Yes"
  }
];
